### ISSUE TITLE
Run tests with system-based Ubuntu 20.04 image

### ISSUE THREAD

**Issue by udosson** [hyperledger/indy-test-automation#113]
It seems like the Nodes in the test network don't reach consensus according to their logs. 

Steps to reproduce:
1. Check out https://github.com/udosson/indy-test-automation/tree/test-systemd-ubuntu-2004
2. Follow the [readme](https://github.com/udosson/indy-test-automation/blob/test-systemd-ubuntu-2004/system_node_only/docker/README.md) and use the ubuntu 20.04 commands

When running the tests and thereby starting the docker containers it seems like the nodes connect, lose connection, and reconnect to the nodes. 
The tests get stuck in the following function
https://github.com/udosson/indy-test-automation/blob/test-systemd-ubuntu-2004/system_node_only/utils.py#L522

[Node1.log](https://github.com/hyperledger/indy-test-automation/files/8350261/Node1.log)
[Node2.log](https://github.com/hyperledger/indy-test-automation/files/8350262/Node2.log)
[Node3.log](https://github.com/hyperledger/indy-test-automation/files/8350263/Node3.log)
[Node4.log](https://github.com/hyperledger/indy-test-automation/files/8350264/Node4.log)
[Node5.log](https://github.com/hyperledger/indy-test-automation/files/8350265/Node5.log)
[Node6.log](https://github.com/hyperledger/indy-test-automation/files/8350266/Node6.log)
[Node7.log](https://github.com/hyperledger/indy-test-automation/files/8350267/Node7.log)

Any ideas @WadeBarnes and @pSchlarb?

**Comment by WadeBarnes** [comment]
It looks like they can't stablish a connection with each other.  Investigating.

**Comment by WadeBarnes** [comment]
The `indy-node-control.service` is scheduling restarts of `indy-node` for some reason.

**Comment by WadeBarnes** [comment]
The `indy-node-control.service` is crashing and restarting, which may be contributing to the `indy-node` restarts.  I'm looking into why it's crashing and seeing if fixing that solves the `indy-node` restart issues.

**Comment by WadeBarnes** [comment]
Fixing the crash in `indy-node-control.service` worked for a shorter set of tests `UBUNTU_VERSION="ubuntu-2004" ./run.sh system_node_only/indy-node-tests/test_ledger.py "-l -v --junit-xml=test_ledger-report.xml -k test_send_and_get_nym_positive".  Running the longer set of tests tom confirm; `UBUNTU_VERSION="ubuntu-2004" ./run.sh system_node_only/indy-node-tests/test_ledger.py "-l -v --junit-xml=test_ledger-report.xml --log-cli-level 0"`

**Comment by WadeBarnes** [comment]
When the `indy-node-control.service` starts up it attempts to hold indy and plenum related packages from this list, https://github.com/hyperledger/indy-node/blob/ubuntu-20.04-upgrade/indy_common/config.py#L100-L107.  In the case of the 20.04 version of node, the `python3-pygments` and `python3-intervaltree` packages do not exist.  When the `indy-node-control.service` tries to hold these packages it crashes and restarts.  The restart of the `indy-node-control.service` seems to also trigger a restart of the `node-service`.  I'm not sure exactly why or how, as I have not dug into the specifics, but on the surface it does not appear to be related to the `indy-node-control.service` code itself.

**Comment by WadeBarnes** [comment]
I tested this by installing the two packages into the node container at the `indy-test-automation` level:
![image](https://user-images.githubusercontent.com/10504350/160708177-dadd7033-acf0-4bad-902a-7ed102e42611.png)

**Comment by WadeBarnes** [comment]
Fix is here; https://github.com/hyperledger/indy-node/pull/1741

**Comment by WadeBarnes** [comment]
@udosson, I've updated the instructions with the fixed version on `indy-node` on your branch here; https://github.com/udosson/indy-test-automation/pull/1.
