### ISSUE TITLE
Issue Unable to start indy-node docker with chaos

### ISSUE THREAD

**Issue by NidhishVyas** [hyperledger/indy-test-automation#139]
I added the files of chaos in indy node and tried to start the pool. However, I recieve the following errors despite removing all images and rebuilding. What is the issue? Thanks

Node Node4 0.0.0.0 9707 0.0.0.0 9708 created
Writing pool data node1 10.0.0.2 9701 9702,node2 10.0.0.3 9703 9704,node3 10.0.0.4 9705 9706,node4 10.0.0.5 9707 9708 to file pool_data
Pool created
Reading pool data
Pool data is node1 10.0.0.2 9701 9702,node2 10.0.0.3 9703 9704,node3 10.0.0.4 9705 9706,node4 10.0.0.5 9707 9708
Creating pool network pool-network
e1847d60175a92385bf2cd212d95cbbf7d6f0a3e105f985ec51f07b65684c3aa
Starting pool
Starting node node1 10.0.0.2
b23eec11c4bf3de84af0d712dbc905c27421669a00f7f7850bf59f477c8ccd85
Error response from daemon: Container b23eec11c4bf3de84af0d712dbc905c27421669a00f7f7850bf59f477c8ccd85 is not running

**Comment by WadeBarnes** [comment]
@NidhishVyas, The chaos tests are likely out of date.  Work over the past few years has focused on the system tests.  Is the work you've done somewhere accessible?  If so and you can provide detailed steps to reproduce, I can have a quick look when I have some spare time.

**Comment by NidhishVyas** [comment]
Hey, I managed to figure that out. I was facing another issue though. Was trying the build from csv in performance folder as well in scripts folder. But where can I generate the csv metric for the graph of the performance of my node? Thanks
